from __future__ import annotations

# ---------------------------------------------------------------------------
# RATIONALES
# Same nested key structure as charts.py but values are snake_case strings.
# Top-level keys: "hard", "soft", "pair"
# Second-level keys: player total (int) or pair rank (str)
# Third-level keys: dealer up-card (int, 11 = Ace)
# Usage: RATIONALES["hard"][16][10] -> coaching tag for rule_coach.py
# ---------------------------------------------------------------------------

RATIONALES: dict = {
    "hard": {
        4:  {2: "hit_low_total_no_bust_risk", 3: "hit_low_total_no_bust_risk", 4: "hit_low_total_no_bust_risk", 5: "hit_low_total_no_bust_risk", 6: "hit_low_total_no_bust_risk", 7: "hit_low_total_no_bust_risk", 8: "hit_low_total_no_bust_risk", 9: "hit_low_total_no_bust_risk", 10: "hit_low_total_no_bust_risk", 11: "hit_low_total_no_bust_risk"},
        5:  {2: "hit_low_total_no_bust_risk", 3: "hit_low_total_no_bust_risk", 4: "hit_low_total_no_bust_risk", 5: "hit_low_total_no_bust_risk", 6: "hit_low_total_no_bust_risk", 7: "hit_low_total_no_bust_risk", 8: "hit_low_total_no_bust_risk", 9: "hit_low_total_no_bust_risk", 10: "hit_low_total_no_bust_risk", 11: "hit_low_total_no_bust_risk"},
        6:  {2: "hit_low_total_no_bust_risk", 3: "hit_low_total_no_bust_risk", 4: "hit_low_total_no_bust_risk", 5: "hit_low_total_no_bust_risk", 6: "hit_low_total_no_bust_risk", 7: "hit_low_total_no_bust_risk", 8: "hit_low_total_no_bust_risk", 9: "hit_low_total_no_bust_risk", 10: "hit_low_total_no_bust_risk", 11: "hit_low_total_no_bust_risk"},
        7:  {2: "hit_low_total_no_bust_risk", 3: "hit_low_total_no_bust_risk", 4: "hit_low_total_no_bust_risk", 5: "hit_low_total_no_bust_risk", 6: "hit_low_total_no_bust_risk", 7: "hit_low_total_no_bust_risk", 8: "hit_low_total_no_bust_risk", 9: "hit_low_total_no_bust_risk", 10: "hit_low_total_no_bust_risk", 11: "hit_low_total_no_bust_risk"},
        8:  {2: "hit_low_total_no_bust_risk", 3: "hit_low_total_no_bust_risk", 4: "hit_low_total_no_bust_risk", 5: "hit_low_total_no_bust_risk", 6: "hit_low_total_no_bust_risk", 7: "hit_low_total_no_bust_risk", 8: "hit_low_total_no_bust_risk", 9: "hit_low_total_no_bust_risk", 10: "hit_low_total_no_bust_risk", 11: "hit_low_total_no_bust_risk"},
        9:  {2: "hit_9_vs_strong_dealer", 3: "double_9_vs_dealer_bust_range", 4: "double_9_vs_dealer_bust_range", 5: "double_9_vs_dealer_bust_range", 6: "double_9_vs_dealer_bust_range", 7: "hit_9_vs_neutral_dealer", 8: "hit_9_vs_strong_dealer", 9: "hit_9_vs_strong_dealer", 10: "hit_9_vs_strong_dealer", 11: "hit_9_vs_strong_dealer"},
        10: {2: "double_10_vs_dealer_bust_range", 3: "double_10_vs_dealer_bust_range", 4: "double_10_vs_dealer_bust_range", 5: "double_10_vs_dealer_bust_range", 6: "double_10_vs_dealer_bust_range", 7: "double_10_vs_neutral_dealer", 8: "double_10_vs_neutral_dealer", 9: "double_10_vs_neutral_dealer", 10: "hit_10_vs_strong_dealer_no_double_edge", 11: "hit_10_vs_strong_dealer_no_double_edge"},
        11: {2: "double_11_best_starting_total", 3: "double_11_best_starting_total", 4: "double_11_best_starting_total", 5: "double_11_best_starting_total", 6: "double_11_best_starting_total", 7: "double_11_best_starting_total", 8: "double_11_best_starting_total", 9: "double_11_best_starting_total", 10: "double_11_vs_strong_dealer_still_positive_ev", 11: "hit_11_vs_dealer_ace_no_double_advantage"},
        12: {2: "hit_12_vs_neutral_dealer_dealer_bust_rate_low", 3: "hit_12_vs_neutral_dealer_dealer_bust_rate_low", 4: "stand_12_vs_dealer_bust_range", 5: "stand_12_vs_dealer_bust_range", 6: "stand_12_vs_dealer_bust_range", 7: "hit_12_vs_strong_dealer", 8: "hit_12_vs_strong_dealer", 9: "hit_12_vs_strong_dealer", 10: "hit_12_vs_strong_dealer", 11: "hit_12_vs_strong_dealer"},
        13: {2: "stand_vs_dealer_bust_range", 3: "stand_vs_dealer_bust_range", 4: "stand_vs_dealer_bust_range", 5: "stand_vs_dealer_bust_range", 6: "stand_vs_dealer_bust_range", 7: "hit_vs_strong_dealer_must_improve", 8: "hit_vs_strong_dealer_must_improve", 9: "hit_vs_strong_dealer_must_improve", 10: "hit_vs_strong_dealer_must_improve", 11: "hit_vs_strong_dealer_must_improve"},
        14: {2: "stand_vs_dealer_bust_range", 3: "stand_vs_dealer_bust_range", 4: "stand_vs_dealer_bust_range", 5: "stand_vs_dealer_bust_range", 6: "stand_vs_dealer_bust_range", 7: "hit_vs_strong_dealer_must_improve", 8: "hit_vs_strong_dealer_must_improve", 9: "hit_vs_strong_dealer_must_improve", 10: "hit_vs_strong_dealer_must_improve", 11: "hit_vs_strong_dealer_must_improve"},
        15: {2: "stand_vs_dealer_bust_range", 3: "stand_vs_dealer_bust_range", 4: "stand_vs_dealer_bust_range", 5: "stand_vs_dealer_bust_range", 6: "stand_vs_dealer_bust_range", 7: "hit_15_vs_neutral_dealer", 8: "hit_15_vs_neutral_dealer", 9: "hit_15_vs_neutral_dealer", 10: "surrender_15_high_bust_risk_vs_strong_dealer", 11: "surrender_15_high_bust_risk_vs_strong_dealer"},
        16: {2: "stand_vs_dealer_bust_range", 3: "stand_vs_dealer_bust_range", 4: "stand_vs_dealer_bust_range", 5: "stand_vs_dealer_bust_range", 6: "stand_vs_dealer_bust_range", 7: "hit_16_vs_neutral_dealer", 8: "hit_16_vs_neutral_dealer", 9: "surrender_16_negative_ev_vs_strong_dealer", 10: "surrender_16_negative_ev_vs_strong_dealer", 11: "surrender_16_negative_ev_vs_strong_dealer"},
        17: {2: "stand_pat_17_or_better", 3: "stand_pat_17_or_better", 4: "stand_pat_17_or_better", 5: "stand_pat_17_or_better", 6: "stand_pat_17_or_better", 7: "stand_pat_17_or_better", 8: "stand_pat_17_or_better", 9: "stand_pat_17_or_better", 10: "stand_pat_17_or_better", 11: "stand_pat_17_or_better"},
        18: {2: "stand_pat_17_or_better", 3: "stand_pat_17_or_better", 4: "stand_pat_17_or_better", 5: "stand_pat_17_or_better", 6: "stand_pat_17_or_better", 7: "stand_pat_17_or_better", 8: "stand_pat_17_or_better", 9: "stand_pat_17_or_better", 10: "stand_pat_17_or_better", 11: "stand_pat_17_or_better"},
        19: {2: "stand_pat_17_or_better", 3: "stand_pat_17_or_better", 4: "stand_pat_17_or_better", 5: "stand_pat_17_or_better", 6: "stand_pat_17_or_better", 7: "stand_pat_17_or_better", 8: "stand_pat_17_or_better", 9: "stand_pat_17_or_better", 10: "stand_pat_17_or_better", 11: "stand_pat_17_or_better"},
        20: {2: "stand_pat_17_or_better", 3: "stand_pat_17_or_better", 4: "stand_pat_17_or_better", 5: "stand_pat_17_or_better", 6: "stand_pat_17_or_better", 7: "stand_pat_17_or_better", 8: "stand_pat_17_or_better", 9: "stand_pat_17_or_better", 10: "stand_pat_17_or_better", 11: "stand_pat_17_or_better"},
        21: {2: "stand_pat_17_or_better", 3: "stand_pat_17_or_better", 4: "stand_pat_17_or_better", 5: "stand_pat_17_or_better", 6: "stand_pat_17_or_better", 7: "stand_pat_17_or_better", 8: "stand_pat_17_or_better", 9: "stand_pat_17_or_better", 10: "stand_pat_17_or_better", 11: "stand_pat_17_or_better"},
    },
    "soft": {
        13: {2: "hit_soft_improve_weak_total", 3: "hit_soft_improve_weak_total", 4: "hit_soft_improve_weak_total", 5: "double_soft_vs_weak_dealer_two_ways_to_win", 6: "double_soft_vs_weak_dealer_two_ways_to_win", 7: "hit_soft_improve_weak_total", 8: "hit_soft_improve_weak_total", 9: "hit_soft_improve_weak_total", 10: "hit_soft_improve_weak_total", 11: "hit_soft_improve_weak_total"},
        14: {2: "hit_soft_improve_weak_total", 3: "hit_soft_improve_weak_total", 4: "hit_soft_improve_weak_total", 5: "double_soft_vs_weak_dealer_two_ways_to_win", 6: "double_soft_vs_weak_dealer_two_ways_to_win", 7: "hit_soft_improve_weak_total", 8: "hit_soft_improve_weak_total", 9: "hit_soft_improve_weak_total", 10: "hit_soft_improve_weak_total", 11: "hit_soft_improve_weak_total"},
        15: {2: "hit_soft_improve_weak_total", 3: "hit_soft_improve_weak_total", 4: "double_soft_vs_dealer_bust_range", 5: "double_soft_vs_dealer_bust_range", 6: "double_soft_vs_dealer_bust_range", 7: "hit_soft_improve_weak_total", 8: "hit_soft_improve_weak_total", 9: "hit_soft_improve_weak_total", 10: "hit_soft_improve_weak_total", 11: "hit_soft_improve_weak_total"},
        16: {2: "hit_soft_improve_weak_total", 3: "hit_soft_improve_weak_total", 4: "double_soft_vs_dealer_bust_range", 5: "double_soft_vs_dealer_bust_range", 6: "double_soft_vs_dealer_bust_range", 7: "hit_soft_improve_weak_total", 8: "hit_soft_improve_weak_total", 9: "hit_soft_improve_weak_total", 10: "hit_soft_improve_weak_total", 11: "hit_soft_improve_weak_total"},
        17: {2: "hit_soft_17_draw_to_improvement", 3: "double_soft_17_vs_bust_range_standing_value_negative", 4: "double_soft_17_vs_bust_range_standing_value_negative", 5: "double_soft_17_vs_bust_range_standing_value_negative", 6: "double_soft_17_vs_bust_range_standing_value_negative", 7: "hit_soft_17_draw_to_improvement", 8: "hit_soft_17_draw_to_improvement", 9: "hit_soft_17_draw_to_improvement", 10: "hit_soft_17_draw_to_improvement", 11: "hit_soft_17_draw_to_improvement"},
        18: {2: "double_soft_18_vs_bust_range_gain_on_strong_total", 3: "double_soft_18_vs_bust_range_gain_on_strong_total", 4: "double_soft_18_vs_bust_range_gain_on_strong_total", 5: "double_soft_18_vs_bust_range_gain_on_strong_total", 6: "double_soft_18_vs_bust_range_gain_on_strong_total", 7: "stand_soft_18_beats_dealer_likely_17", 8: "stand_soft_18_tied_with_dealer_likely_18", 9: "hit_soft_18_vs_strong_dealer_18_loses_too_often", 10: "hit_soft_18_vs_strong_dealer_18_loses_too_often", 11: "hit_soft_18_vs_strong_dealer_18_loses_too_often"},
        19: {2: "stand_soft_19_plus_strong_total", 3: "stand_soft_19_plus_strong_total", 4: "stand_soft_19_plus_strong_total", 5: "stand_soft_19_plus_strong_total", 6: "stand_soft_19_plus_strong_total", 7: "stand_soft_19_plus_strong_total", 8: "stand_soft_19_plus_strong_total", 9: "stand_soft_19_plus_strong_total", 10: "stand_soft_19_plus_strong_total", 11: "stand_soft_19_plus_strong_total"},
        20: {2: "stand_soft_19_plus_strong_total", 3: "stand_soft_19_plus_strong_total", 4: "stand_soft_19_plus_strong_total", 5: "stand_soft_19_plus_strong_total", 6: "stand_soft_19_plus_strong_total", 7: "stand_soft_19_plus_strong_total", 8: "stand_soft_19_plus_strong_total", 9: "stand_soft_19_plus_strong_total", 10: "stand_soft_19_plus_strong_total", 11: "stand_soft_19_plus_strong_total"},
        21: {2: "stand_soft_19_plus_strong_total", 3: "stand_soft_19_plus_strong_total", 4: "stand_soft_19_plus_strong_total", 5: "stand_soft_19_plus_strong_total", 6: "stand_soft_19_plus_strong_total", 7: "stand_soft_19_plus_strong_total", 8: "stand_soft_19_plus_strong_total", 9: "stand_soft_19_plus_strong_total", 10: "stand_soft_19_plus_strong_total", 11: "stand_soft_19_plus_strong_total"},
    },
    "pair": {
        "A": {2: "always_split_aces_maximizes_blackjack_probability", 3: "always_split_aces_maximizes_blackjack_probability", 4: "always_split_aces_maximizes_blackjack_probability", 5: "always_split_aces_maximizes_blackjack_probability", 6: "always_split_aces_maximizes_blackjack_probability", 7: "always_split_aces_maximizes_blackjack_probability", 8: "always_split_aces_maximizes_blackjack_probability", 9: "always_split_aces_maximizes_blackjack_probability", 10: "always_split_aces_maximizes_blackjack_probability", 11: "always_split_aces_maximizes_blackjack_probability"},
        "2": {2: "split_small_pair_vs_dealer_bust_range_das_advantage", 3: "split_small_pair_vs_dealer_bust_range_das_advantage", 4: "split_small_pair_vs_dealer_bust_range_das_advantage", 5: "split_small_pair_vs_dealer_bust_range_das_advantage", 6: "split_small_pair_vs_dealer_bust_range_das_advantage", 7: "split_small_pair_vs_dealer_neutral", 8: "hit_small_pair_vs_strong_dealer", 9: "hit_small_pair_vs_strong_dealer", 10: "hit_small_pair_vs_strong_dealer", 11: "hit_small_pair_vs_strong_dealer"},
        "3": {2: "split_small_pair_vs_dealer_bust_range_das_advantage", 3: "split_small_pair_vs_dealer_bust_range_das_advantage", 4: "split_small_pair_vs_dealer_bust_range_das_advantage", 5: "split_small_pair_vs_dealer_bust_range_das_advantage", 6: "split_small_pair_vs_dealer_bust_range_das_advantage", 7: "split_small_pair_vs_dealer_neutral", 8: "hit_small_pair_vs_strong_dealer", 9: "hit_small_pair_vs_strong_dealer", 10: "hit_small_pair_vs_strong_dealer", 11: "hit_small_pair_vs_strong_dealer"},
        "4": {2: "hit_4s_vs_neutral_dealer", 3: "hit_4s_vs_neutral_dealer", 4: "hit_4s_vs_neutral_dealer", 5: "split_4s_only_vs_weak_dealer_das_creates_edge", 6: "split_4s_only_vs_weak_dealer_das_creates_edge", 7: "hit_4s_vs_neutral_dealer", 8: "hit_4s_vs_neutral_dealer", 9: "hit_4s_vs_neutral_dealer", 10: "hit_4s_vs_neutral_dealer", 11: "hit_4s_vs_neutral_dealer"},
        "5": {2: "never_split_5s_double_as_hard_10", 3: "never_split_5s_double_as_hard_10", 4: "never_split_5s_double_as_hard_10", 5: "never_split_5s_double_as_hard_10", 6: "never_split_5s_double_as_hard_10", 7: "never_split_5s_double_as_hard_10", 8: "never_split_5s_double_as_hard_10", 9: "never_split_5s_double_as_hard_10", 10: "never_split_5s_hit_vs_strong_dealer", 11: "never_split_5s_hit_vs_strong_dealer"},
        "6": {2: "split_6s_vs_dealer_bust_range", 3: "split_6s_vs_dealer_bust_range", 4: "split_6s_vs_dealer_bust_range", 5: "split_6s_vs_dealer_bust_range", 6: "split_6s_vs_dealer_bust_range", 7: "hit_6s_vs_neutral_dealer_12_too_weak_to_stand", 8: "hit_6s_vs_neutral_dealer_12_too_weak_to_stand", 9: "hit_6s_vs_neutral_dealer_12_too_weak_to_stand", 10: "hit_6s_vs_neutral_dealer_12_too_weak_to_stand", 11: "hit_6s_vs_neutral_dealer_12_too_weak_to_stand"},
        "7": {2: "split_7s_improve_from_weak_14", 3: "split_7s_improve_from_weak_14", 4: "split_7s_improve_from_weak_14", 5: "split_7s_improve_from_weak_14", 6: "split_7s_improve_from_weak_14", 7: "split_7s_vs_dealer_7_create_two_17s", 8: "hit_7s_vs_strong_dealer_14_must_improve", 9: "hit_7s_vs_strong_dealer_14_must_improve", 10: "hit_7s_vs_strong_dealer_14_must_improve", 11: "hit_7s_vs_strong_dealer_14_must_improve"},
        "8": {2: "always_split_8s_16_is_worst_hand", 3: "always_split_8s_16_is_worst_hand", 4: "always_split_8s_16_is_worst_hand", 5: "always_split_8s_16_is_worst_hand", 6: "always_split_8s_16_is_worst_hand", 7: "always_split_8s_16_is_worst_hand", 8: "always_split_8s_16_is_worst_hand", 9: "always_split_8s_16_is_worst_hand", 10: "always_split_8s_16_is_worst_hand", 11: "always_split_8s_16_is_worst_hand"},
        "9": {2: "split_9s_18_beats_dealer_bust_range", 3: "split_9s_18_beats_dealer_bust_range", 4: "split_9s_18_beats_dealer_bust_range", 5: "split_9s_18_beats_dealer_bust_range", 6: "split_9s_18_beats_dealer_bust_range", 7: "stand_9s_vs_7_already_winning_hand_likely_17", 8: "split_9s_18_doesnt_beat_dealers_likely_18_or_19", 9: "split_9s_18_doesnt_beat_dealers_likely_19", 10: "stand_9s_vs_10_splitting_creates_more_losing_hands", 11: "stand_9s_vs_ace_splitting_creates_more_losing_hands"},
        "T": {2: "never_split_10s_20_is_near_unbeatable", 3: "never_split_10s_20_is_near_unbeatable", 4: "never_split_10s_20_is_near_unbeatable", 5: "never_split_10s_20_is_near_unbeatable", 6: "never_split_10s_20_is_near_unbeatable", 7: "never_split_10s_20_is_near_unbeatable", 8: "never_split_10s_20_is_near_unbeatable", 9: "never_split_10s_20_is_near_unbeatable", 10: "never_split_10s_20_is_near_unbeatable", 11: "never_split_10s_20_is_near_unbeatable"},
    },
}
